### ISSUE TITLE
Include "Gesamt" tab in `cumulative_time_series.csv`

### ISSUE THREAD

**Issue by favstats** [favstats/vaccc19de_dashboard#18]
In the RKI .xlsx there is a row with the total Germany-wide data. 

Right now this data is dropped in the cleaning process but it seems like we should keep it. 

That way we can display that data rather than having to calculate it for the dashboard afterwards.

Would you agree @friep?

**Comment by pr130** [comment]
@favstats do you mean the gesamt row or the "new" tab "Impfungen_proTag"? 
i will definitely work on storing the new tab as a separate csv. re the row.. i mean we could include it as an additional _column_. i don't really like keeping at as a row..it feels quite..untidy 🙈

**Comment by favstats** [comment]
I did mean the "Gesamt" row. We can do it as a column sure! But we should keep it in some way.

**Comment by favstats** [comment]
This is irrelevant now because we don't retrieve the data ourselves. So we can close.
